# Generated by Django 4.2.16 on 2025-04-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
